apiVersion: v1 
kind: Pod
metadata: 
  name: pods-multi 
  namespace: dev-pod
  labels: 
    name: mohan 
    purpose: nothign just for fun 
    fuck: not yet
spec: 
  containers:
    - name: nginx 
      image: nginx 
      ports:
        - containerPort: 80 
      resources: 
        requests: 
          cpu: "100m"
          memory: "128Mi"
        limits: 
          cpu: "200m"
          memory: "256Mi"
  
