apiVersion: v1 
kind: Pod
metadata: 
  name: pods-multi 
  namespace: dev-pod
  labels: 
    name: mohan 
    purpose: nothign 
spec: 
  containers:
    - name: nginx 
      image: nginx 
      ports:
        - containerPort: 80 
      resources: 
        requests: 
          cpu: "100m"
          memory: "128Mi"
        limits: 
          cpu: "200m"
          memory: "256Mi"
      env: 
      - name: dev 
        value: this is an dev environemt
      - name: purpose
        value: best way to do it 
  
