apiVersion: v1 
kind: Pod 
metadata:
  name: mohan-pod2
  namespace: dev-pod 
spec: 
  containers:
    - name: mohan
      image: nginx
      env : 
      - name: name
        valueFrom: 
          configMapKeyRef: 
            name: mohan-pod 
            key: name