apiVersion: v1
kind: Pod 
metadata:
  name: env-pod 
spec: 
  containers:
    - name: nginx 
      image: nginx 
      env: 
      - name: demo_greeting 
        value : "thhis is the mohane who are you "
      - name: name_mohan
        value: "this is the mohan who are you "