apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
    - name: my-container
      image: my-image
      env:
        - name: DATABASE_URL
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: database-url
        - name: API_KEY
          valueFrom:
            configMapKeyRef:
              name: example-config
              key: api-key
