apiVersion: v1 
kind: Pod 
metadata:
  name: next-pod 
  namespace: dev-pod
  labels:
    name: mohan 
    age: six
spec: 
  containers: 
    - name: nginx 
      image: nginx 
      ports: 
       - containerPort: 80 
