apiVersion: v1 
kind: Service 
metadata: 
  name: cluster-ip 
  namespace: dev-pod
spec: 
  selector:
    name: mohan 
    age: six 
  ports: 
    - protocol: TCP
      port : 80 
      targetPort: 80