apiVersion: v1 
kind: Service 
metadata: 
  name: node-port 
  namespace: dev
spec: 
  type: NodePort
  selector:
    name: mohan 
    age: six 
  ports: 
    - protocol: TCP
      port : 80 
      targetPort: 80
      