apiVersion: v1 
kind: Pod 
metadata: 
  name: simple-pod 
  namespace: dev
  labels: 
    name: mohan 
    age: six
spec: 
  containers: 
    - name: nginx 
      image: nginx 
      ports: 
        - containerPort: 80 


