apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: nginx-deployment 
  namespace: dev
  labels: 
    name: deployment 
    use: fordeployment 
spec: 
  replicas: 10 
  selector:
    matchLabels: 
      name: frontend 
      database: mysql 
  template: 
    metadata:
      name: mohan-pod 
      labels:
        name: frontend
        database: mysql 
    spec: 
      containers:
        - name: nginx 
          image: nginx:latest