apiVersion: v1 
kind: Pod 
metadata: 
  name: mohan-pod 
  namespace: dev 
spec: 
  volumes: 
  - name: nginx-conf 
    configMap:
      name: config-conf
      items: 
      - key: nginx.conf 
        path: nginx.conf
  containers:
  - name: mohan 
    image: nginx 
    volumeMounts: 
    - name: nginx-conf 
      mountPath: /etc/nginx/nginx.conf 
      subPath: nginx.conf 
      readOnly: true 