apiVersion: v1
kind: Pod
metadata:
  name: pod-with-sidecar
spec:
  containers:
  - name: main-container
    image: nginx
    ports:
    - containerPort: 80
  - name: sidecar-container
    image: busybox
    command: ['sh', '-c', 'echo Hello from the sidecar container && sleep 3600']
