apiVersion: v1
kind: Pod
metadata:
  name: service-pod
  labels:
    name: mohan
    status: waste
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    name: mohan
    status: waste
  ports:
  - name: name-of-the
    protocol: TCP
    port: 80
    targetPort: http
