apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-deployment
  labels:
    app: catalogue
    owner: mohan
spec:
  replicas: 1
  selector:
    matchLabels:
      name: catalogue
      owner: mohan
  template:
    metadata:
      labels:
        name: catalogue
        owner: mohan
    spec:
      containers:
        - name: catalogue
          image: joindevops/catalogue:1.0.0
          envFrom:
            - configMapRef:
                name: config-map  # Corrected indentation
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
  labels:
    name: catalogue
    owner: mohan
spec:
  selector:
    name: catalogue   # Corrected selector
    owner: mohan     # Corrected selector
  ports:
    - name: catalogue-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: config-map 
  namespace: dev 
data: 
  MONGO: "true"
  MONGO_URL: "mongodb://cluster-ip:27017/catalogue"
