apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: redis 
  namespace: dev 
  labels: 
    name: redis 
    owner: mohan 
spec: 
  replicas: 3 
  selector:
    matchLabels:
      name: redis 
      owner: mohan 
  template: 
    metadata: 
      name: redis 
        
      labels: 
        name: redis 
        owner: mohan 
    spec: 
      containers: 
        - name: redis 
          image: redis 
--- 
apiVersion: v1 
kind: Service 

metadata: 
  name: cluster-ip1 
  labels: 
    name: mohan 
    app: redis 
spec: 
  selector: 
    name: redis 
    owner: mohan 
  ports: 
    - name: redis-port 
      protocol: TCP 
      port: 6379
      targetPort: 6379

      
  