apiVersion: v1 
kind: Deployment 
metadata: 
  name: mongodb
  namespace: dev 
  labels: 
    app: mongodb 
    owner: mohan 
spec: 
  replicas: 1 
  selector: 
    matchLabels: 
      app: mongodb 
      owner: mohan 
  template: 
    metadata: 
      name: mongodb-database 
      app: mongodb 
      owner: mohan 
    spec: 
      containers: 
        - name: mongodb 
          image: 