apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: dev
  labels:
    app: mongodb
    owner: mohan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      owner: mohan
  template:
    metadata:
      labels:    # Corrected field name
        app: mongodb
        owner: mohan
    spec:
      containers:
        - name: mongodb
          image: mohan9676/mongodb:1.0.0
---
apiVersion: v1 
kind: Service 
metadata: 
  name: cluster-ip 
  namespace: dev
spec: 
  selector: 
    app: mongodb 
    owner: mohan 
  ports: 
    - name: mongodb-port 
      protocol: TCP 
      port: 27017 
      targetPort: 27017
