apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mongodb-deployement 
  namespace: dev 
  labels: 
    service: mongodb 
    owner: mohan 
    kind: database 
spec: 
  replicas: 10
  selector:
    matchLabels:
      name: mongodb 
      kind: database 
      owner: mohan 
  template:
    metadata: 
      name: mongodb 
      labels: 
        name: mongodb 
        kind: database
        owner: mohan 
    spec: 
      containers: 
        - name: mongodb 
          image: joindevops/mongodb:1.0.0
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: cluster-ip 
  namespace: dev 
  labels: 
    name: cluster 
    use: accesible 
spec:
  clusterIP: None 
  selector:
    name: mongodb
    kind: database
    owner: mohan
  ports:
    - name: mongodb-port 
      protocol: TCP 
      port: 27017
      targetPort: 27017
      