apiVersion: apps/v1 
kind: DaemonSet 
metadata: 
  name: fluentd 
  namespace: kube-system
  labels: 
    app: roboshop 
    environment: dev 
spec: 
  selector: 
    matchLabels: 
      app: roboshop 
      environment: dev 
  template: 
    metadata: 
      name: mohan-nginx-pod 
      labels: 
        app: roboshop 
        environment: dev 
    spec:
      containers:
        - name: fluentd 
          image: quay.io/fluentd_elasticsearch/fluentd:v1.5.2 
          resources: 
            limits: 
              memory: 200Mi
            requests: 
              cpu: 100m 
              memory: 200Mi 
      volumes: 
      - name: varlog 
        hostPath: 
          path: /var/log 