apiVersion:  v1 
kind: ConfigMap 
metadata: 
  name: filebeat-configuration 
data: 
  filebeat.yaml: |
    filebeat: 
      config: 
        module: 
          path; /usr/share/filebeat/modules.d/*.yml
          reload:
            enabled: true 
      modules: 
      - module: nginx 
        access: 
          var.paths: ["/var/log/nginx/access.log*"]
        error:
          var.paths: ["/var/log/nginx/error.log*"]
    output:
      elasticsearch: 
        hosts: ["elasticsearch:9200""]
--- 
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: nginx 
  labels: 
    app: logs 
    environment: dev 
spec: 
  replicas: 1 
  selector: 
    matchLabels:
      app: logs 
      environment: dev 
  template: 
    metadata: 
      name: mohan-pod 
      labels: 
        app: logs 
        environment: dev 
    spec: 
      containers: 
        - name: mohan-conatiner 
          image: nginx 
          ports:
            - containerPort: 80 
          volumeMounts: 
            - name: nginx-logs 
              mountPath: var/log/nginx/
        - name: filebeat-sidecar 
          image: docker.elastic.co/beats/filebeat:7.5.0 
          volumeMounts: 
            - name: nginx-logs 
              mountPath: var/log/nginx/ 
            - name: filebeat-config
              mountPath: /usr/share/filebeat/filebeat.yml
              subPath: filebeat.yml 
      volumes:
        - name: nginx-logs 
        - name: filebeat-config 
          configMap:
            name: filebeat-config 
            items:
              - key: filebeat.yml
                path: filebeat.yml