apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: eks-static 
spec: 
  accessModes: 
    - ReadWriteOnce 
  awsElasticBlockStore: 
    fsType: ext4 
    volumeID: vol-0d56f5b6940554c53
  capacity: 
    storage: 7Gi