apiVersion: v1
kind: PersistentVolume
metadata:
  name: eks-static
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0b9a9bb604b13444b  # Replace <YOUR_EBS_VOLUME_ID> with the actual EBS volume ID
  capacity:
    storage: 7Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-static-pvc
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
--- 
apiVersion: apps/v1
kind: Deployment 
metadata: 
  name: mohan-nginx 
  labels: 
    app: roboshop 
    environment: prod 
spec: 
  replicas: 10 
  selector: 
    matchLabels: 
      app: roboshop 
      environment: prod 
  template: 
    metadata: 
      name: nginx_pod 
      labels: 
        app: roboshop 
        environment: prod 
    spec: 
      containers:
        - name: mohan-container 
          image: nginx 
          ports: 
            - containerPort: 80 
          volumeMounts: 
            - name: pvc 
              mountPath: "/usr/share/nginx/html"  # Corrected mountPath
      volumes: 
        - name: pvc 
          persistentVolumeClaim:  # Corrected persistentVolumeClaim
            claimName: ebs-static-pvc  # Corrected claimName
