apiVersion: v1 
kind: PersistentVolume 
metadata: 
  name: eks-static 
spec: 
  storageClassName: ""
  accessModes: 
    - ReadWriteOnce 
  awsElasticBlockStore: 
    fsType: ext4 
    volumeID: vol-0d56f5b6940554c53
  capacity: 
    storage: 7Gi
--- 
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: ebs-static-pvc 
spec: 
  storageClassName: ""
  accessModes: 
    - ReadWriteOnce 
  resources: 
    requests: 
      storage: 2Gi